export const autodescubrimientoData = {
  areas: {
    administracion: {
      title: "Administración, Economía y Negocios",
      talentos: [
        "Trabajar con números",
        "Iniciar proyecto propio",
        "Liderar",
        "Asumir riesgos",
        "Tareas de oficina",
        "Manejar contabilidad",
        "Convencer a otros",
        "Llevar cuentas",
        "Supervisar",
        "Detectar oportunidades",
        "Planificar ganancias",
        "Diseñar inversiones",
      ],
    },
    sociales: {
      title: "Sociales y RRHH",
      talentos: [
        "Ayudar a otros",
        "Percibir necesidades",
        "Leer sobre problemas sociales",
        "Tareas solidarias",
        "Aconsejar",
        "Incentivar relaciones",
        "Actividades con niños/ancianos",
        "Contención emocional",
        "Trabajo en equipo",
        "Interés en conducta humana",
      ],
    },
    humanidades: {
      title: "Humanidades, Educación y Psicología",
      talentos: [
        "Enseñar/Entrenar",
        "Idiomas",
        "Facilitar comunicación",
        "Planear recreación",
        "Interés educativo",
        "Talleres literarios/culturales",
        "Retiros espirituales",
        "Hablar en público",
        "Escribir",
        "Reflexión filosófica",
        "Leer",
      ],
    },
    salud: {
      title: "Salud",
      talentos: [
        "Anatomía/Fisiología",
        "Investigación en salud",
        "Ayudar enfermos",
        "Leer sobre medicina",
        "Voluntariado hospitalario",
        "Prevención",
        "Emergencias",
        "Primeros auxilios",
        "Nutrición",
      ],
    },
    juridicas: {
      title: "Jurídicas, Políticas y Seguridad",
      talentos: [
        "Seguridad de los demás",
        "Relaciones internacionales",
        "Defensa del territorio",
        "Política",
        "Noticias delictivas",
        "Defender causas justas",
        "Conciliar disputas",
        "Prevención del delito",
        "Defender derechos",
        "Juzgar con objetividad",
      ],
    },
    ecologia: {
      title: "Ecología y Naturaleza",
      talentos: [
        "Medio ambiente",
        "Alimentación humana",
        "Reservas animales",
        "Preservación de especies",
        "Actividad agrícola/ganadera",
        "Crianza de animales",
        "Biología/Ecología",
        "Vida marina",
        "Cocina",
        "Genética",
        "Geografía",
      ],
    },
    exactas: {
      title: "Exactas, Ingeniería y Sistemas",
      talentos: [
        "Relacionar teorías",
        "Organizar objetos/datos",
        "Informática",
        "Programar software",
        "Lógica",
        "Leer revistas científicas",
        "Cálculos complejos",
        "Fórmulas matemáticas/químicas",
        "Manipular herramientas",
        "Experimentos",
        "Reparaciones",
      ],
    },
    comunicacion: {
      title: "Comunicación y Medios",
      talentos: [
        "Promocionar",
        "Indagar culturas/historia",
        "Planificar viajes/eventos",
        "Luces y sonido",
        "Relatar",
        "Crítica de espectáculos",
        "Periodismo",
        "Operar sistemas electrónicos",
        "Transmitir comunicación",
        "Entrevistar",
        "Organizar eventos",
      ],
    },
    arte: {
      title: "Arte y Diseño",
      talentos: [
        "Decorar",
        "Leer partituras",
        "Historia del arte",
        "Tocar instrumento",
        "Fotografía",
        "Danza",
        "Teatro",
        "Diseño de objetos/imágenes",
        "Dibujar/Pintar",
        "Manualidades/Escultura",
        "Confección de ropa",
        "Maquetas",
        "Diseño web",
      ],
    },
  },
  autobiografiaFields: [
    { id: "yo", label: "Yo", description: "¿Quién soy hoy? ¿Cómo me definiría en pocas palabras?" },
    { id: "retrato", label: "Retrato", description: "¿Cómo soy físicamente y cómo soy como persona? (forma de ser, carácter, actitudes)" },
    { id: "origenes", label: "Orígenes", description: "Mi familia, mi casa, mi barrio. ¿Qué cosas de ahí siento que me marcaron?" },
    { id: "pasado", label: "Pasado", description: "Mi infancia, mis juegos, mis amigos y mi escuela. ¿Qué recuerdo de esa etapa?" },
    { id: "perfil", label: "Perfil", description: "Mis intereses y habilidades. Lo que se me da bien, lo que me gusta hacer, mis hábitos, gustos y ambiciones." },
    { id: "memorias", label: "Memorias", description: "Mis mejores recuerdos y los más difíciles. ¿Qué edades o momentos fueron los más lindos? ¿Cuáles los más complicados?" },
    { id: "presente", label: "Presente", description: "Cómo es mi vida hoy. Qué cosas me alegran y qué cosas me preocupan actualmente." },
    { id: "futuro", label: "Futuro", description: "Mis sueños y proyectos. Cómo me imagino en algunos años y qué me gustaría lograr." },
    { id: "satisfaccion", label: "Recuerdo de Satisfacción", description: "Recuperá de tu memoria dos hechos que te hayan producido mucha satisfacción donde hayas tenido un papel activo (no como espectador). Describí esos dos hechos inolvidables." },
  ],
  estilosAprendizajePreguntas: [
    {
      question: "¿Qué tipo de examen realizas con mayor facilidad?",
      options: ["Escrito", "Oral", "Opción múltiple"],
    },
    {
      question: "Cuando tenés que aprender algo de memoria…",
      options: ["Memorizo imagen", "Repito rítmicamente", "Paseo y miro idea general"],
    },
    {
      question: "En clase te es más fácil seguir explicaciones…",
      options: ["Escuchando", "Me aburro si no hago algo", "Leyendo"],
    },
    {
      question: "Aprendés más fácil:",
      options: ["Repitiendo en voz alta", "Escribiendo varias veces", "Relacionando con algo divertido"],
    },
    {
      question: "Instrucciones:",
      options: ["Me muevo antes de que acaben", "Recuerdo palabras exactas", "Prefiero por escrito"],
    },
    {
      question: "En clase preferís:",
      options: ["Actividades de movimiento", "Material escrito-visual", "Debates y diálogo"],
    },
  ],
  preguntasAbiertas: [
    { id: "felicidad", label: "Felicidad", question: "¿Qué cosas te hacen feliz en el día a día (por más pequeñas que sean)?" },
    { id: "infelicidad", label: "Infelicidad", question: "¿Qué cosas te hacen infeliz (y quisieras evitar o minimizar)?" },
    { id: "exito", label: "Éxito", question: "¿Cómo definirías con tus palabras el \"éxito profesional\"?" },
    { id: "certeza", label: "Certeza", question: "Si supieras con certeza que las próximas cinco cosas que hagas te saldrán exactamente como quieres, ¿cuáles serían estas cinco cosas que elegirías hacer?" },
  ],
}
