export const gardnerQuestions = {
  logicoMatematica: [
    "Puedo calcular números mentalmente con facilidad.",
    "Las matemáticas y/o ciencias estaban entre mis materias favoritas en la escuela.",
    "Me gusta jugar juegos o resolver problemas que requieren pensamiento lógico.",
    "Me gusta armar experimentos de ¿qué pasaría si...?",
    "Mi mente busca los patrones, las regularidades o las secuencias lógicas en las cosas.",
    "Me interesan los nuevos desarrollos de las ciencias.",
    "Creo que casi todo tiene una explicación racional.",
    "A veces pienso en conceptos claros, abstractos, sin palabras y sin imágenes.",
    "Me gusta encontrar defecto lógicos en las cosas que las personas dicen o hacen en su caso o en su trabajo.",
    "Me siento más cómodo cuando algo ha sido medido, categorizado, analizado o cuantificado de algún modo.",
  ],
  linguistica: [
    "Para mí los libros son importantes.",
    "Puedo escuchar las palabras en mi cabeza antes de leerlas, decirlas o escribirlas.",
    "Me resulta más fácil entender una idea escuchando un podcast o un audio que mirando un video o una película.",
    "Me encantan los juegos de ingenio con palabras.",
    "Me agrada entretenerme o entretener a otros con trabalenguas, rimas sin sentido o chistes verbales.",
    "Las otras personas muy a menudo tienen que detenerse y pedirme que explique el significado de las palabras que uso en mis textos escritos o en mi lenguaje hablado.",
    "Lengua, estudios sociales e historia fueron mucho más fáciles para mí en mis años escolares, que la matemática o las ciencias.",
    "Cuando manejo por una autopista o viajo con alguien presto más atención a las palabras escritas en los carteles que al paisaje.",
    "Mi conversación incluye referencias frecuentes a cosas que he leído u oído.",
    "Recientemente escribí algo de lo que me sentí particularmente orgulloso y que me ganó el reconocimiento de otros.",
  ],
  espacial: [
    "Soy sensible a los colores.",
    "Con frecuencia uso una cámara o una grabadora de video para registrar lo que veo a mi alrededor.",
    "Disfruto el armar rompecabezas y resolver problemas visuales.",
    "De noche tengo sueños vívidos.",
    "Me resulta fácil encontrar el camino en lugares nuevos aunque no use el Google Maps.",
    "Me gusta dibujar o hacer dibujitos mientras hago otras cosas (por ejemplo al hablar por teléfono).",
    "Me resulta más fácil entender cómo encajan las piezas de algo, que tratar de resolver problemas que son solo números y letras en una hoja.",
    "Puedo imaginarme como se ve algo físico desde otro punto de vista.",
    "Prefiero los materiales de lectura que tienen muchas ilustraciones.",
  ],
  corporalCinetica: [
    "Practico de manera regular por lo menos un deporte o actividad física.",
    "Me resulta difícil estar sentado durante períodos largos de tiempo.",
    "Me llevo muy bien con las tareas manuales, como armar cosas, arreglar o fabricar algo desde cero con mis manos.",
    "Mis mejores ideas a menudo me vienen cuando he salido a dar una caminata larga o a correr, o mientras estoy ocupado en alguna otra actividad física.",
    "Muy frecuentemente prefiero pasar mi tiempo libre al aire libre.",
    "Soy de esas personas que hablan con todo el cuerpo y necesitan hacer gestos para explicar algo.",
    "Necesito tocar las cosas para saber más de ellas.",
    "Disfruto las actividades físicamente arriesgadas u otras formas similares de acción física que me enfrenten con el peligro.",
    "Me describiría como bien coordinado.",
    "Me gusta practicar una nueva habilidad física más que leer sobre ella o verla representada en una filmación.",
  ],
  musical: [
    "Tengo una voz agradable para cantar.",
    "Puedo darme cuenta cuándo una nota musical está fuera de tono.",
    "Escucho música frecuentemente.",
    "Toco un instrumento musical.",
    "Mi vida sería más pobre si en ella no existiera la música.",
    "Con frecuencia tengo alguna canción o audio viral dándome vueltas en la cabeza.",
    "Me sale natural seguirle el beat a cualquier canción golpeando la mesa o los dedos contra algo.",
    "Tengo una biblioteca mental de letras de canciones que me sé completas de memoria.",
    "Escucho un tema nuevo un par de veces y ya me sale cantarlo sin equivocarme.",
    "Para concentrarme cuando hago algo, suelo estar tarareando o haciendo ruiditos con la boca.",
  ],
  naturalista: [
    "Amo ir a caminar a los bosques y mirar a los árboles y las flores.",
    "Disfruto la jardinería.",
    "Disfruto de la naturaleza y estar al aire libre.",
    "Disfruto aprendiendo los nombres de las seres vivientes de nuestro medio ambiente.",
    "Hago colecciones de piedras, esqueletos, hojas, insectos, mariposas, joyas o flores.",
    "Me gusta pasar a menudo mi tiempo al aire libre, donde pueda correr.",
    "Disfruto la pesca, la caza, la horticultura o sembrar plantas.",
    "Me gusta todo tipo de animales.",
    "Regularmente reviso los informes del estado del clima.",
    "Me gusta alejarme de las ciudades y disfrutar de la naturaleza.",
  ],
  intrapersonal: [
    "De una manera regular paso tiempo solo meditando, reflexionando o pensando en cosas importantes.",
    "He asistido a sesiones de terapia o seminarios de crecimiento personal para aprender más sobre mí mismo.",
    "Soy capaz de resistir los golpes de la vida.",
    "Tengo un hobby o interés personal que por lo general no comparto con otros.",
    "Tengo algunas metas importantes para mi vida sobre la que pienso de manera regular.",
    "Tengo una visión realista de mis fuerzas y de mis debilidades (apoyado en las reacciones de los otros).",
    "Preferiría pasar un fin de semana solo en una cabaña en el bosque antes que en un balneario de moda rodeado de mucha gente.",
    "Considero que poseo una voluntad fuerte y una mente independiente.",
    "Uso las notas del celu o un cuaderno para pasar en limpio lo que siento y lo que me va pasando.",
    "Trabajo por mi cuenta o por lo menos he pensado seriamente en establecerme de manera independiente.",
  ],
  interpersonal: [
    "Mis amigos siempre me eligen como el psicólogo del grupo para contarme sus problemas o pedirme un consejo.",
    "Prefiero los deportes que se practican en grupo, como el fútbol o el voleibol a los deportes solitarios como la natación o carrera de fondo.",
    "Cuando tengo algún problema, lo más frecuente es que busque a otra persona para contárselo y pedirle ayuda antes de tratar de resolverlo por mí mismo.",
    "Tengo por lo menos tres amigos íntimos.",
    "Me divierte mucho más una juntada para jugar a algo en grupo que quedarme solo en frente de una pantalla.",
    "Disfruto el desafío de enseñar a otra persona, o grupos de personas, las cosas que sé hacer.",
    "Me considero un líder u otros me han dicho que lo soy.",
    "Me siento cómodo en medio de una multitud.",
    "Me gusta participar en las actividades sociales que están relacionadas con mi trabajo, iglesia o comunidad.",
    "Prefiero pasar la noche en una fiesta animada antes que quedarme solo en casa.",
  ],
}

export const gardnerLabels = {
  logicoMatematica: "Lógico Matemática",
  linguistica: "Lingüística",
  espacial: "Espacial",
  corporalCinetica: "Corporal Cinética",
  musical: "Musical",
  naturalista: "Naturalista",
  intrapersonal: "Intrapersonal",
  interpersonal: "Interpersonal",
}
