export const gardnerQuestions = {
  logicoMatematica: [
    "Puedo sumar o multiplicar mentalmente con mucha rapidez.",
    "Obtengo conclusiones de una situación y las puedo aplicar a otras semejantes.",
    "Resuelvo acertijos y problemas con valores numéricos.",
    "Puedo predecir posibles desarrollos y consecuencias futuras de un evento o suceso, a partir de la información actual.",
    "Puedo sustentar mis ideas y fundamentarlas con argumentos lógicos.",
    "Capto las relaciones que hay entre las cosas, sus conexiones e interdependencia.",
    "Me gusta utilizar calculadoras o computadoras y sé realizar operaciones complejas.",
    "Me gusta trabajar con números y figuras, captando relaciones o configuraciones entre los mismos.",
    "Resuelvo distintos tipos de problemas aplicando la lógica.",
    "Puedo cuantificar (asignar valores numéricos) a un tema o problema, para resolverlo.",
  ],
  verbalLinguistica: [
    "Disfruto de una buena charla o discurso.",
    "Me gusta escribir poemas, cartas o canciones para otros y lo hago bien.",
    "Disfruto los chistes y los juegos de palabras.",
    "Expreso por escrito en forma comprensible para los demás lo que siento o pienso.",
    "Puedo expresar, explicar o describir con palabras la información que puedo captar o manejar con los otros tipos de inteligencia.",
    "Puedo darme a entender bien hablando en público.",
    "Puedo aprender con facilidad distintos idiomas.",
    "Expreso hablando lo que pienso y siento en forma entendible para otros.",
    "Me importa el significado y la escritura correcta de las palabras y así las empleo.",
    "Entiendo y aprecio las distintas clases de textos escritos y puedo comentarlos.",
  ],
  espacial: [
    "Para estudiar elaboro y utilizo diagramas y gráficos.",
    "Discrimino los matices de los colores y puedo reproducirlos en una pintura o dibujo.",
    "Utilizo imágenes internas para hallar soluciones creativas.",
    "Empleo la imaginación para representar escenas o cosas en mi mente.",
    "Entiendo los gráficos que vienen en las instrucciones de equipos o instrumentos.",
    "Entiendo cómo funcionan las máquinas o aparatos viéndolos o imaginando su interior.",
    "Tengo buena orientación en los distintos lugares o calles.",
    "Descifro mapas complejos con facilidad.",
    "Dibujo y/o pinto en forma creativa o disfruto de hacerlo.",
    "Hago mapas entendibles para explicarle a alguien cómo llegar a un lugar, en vez de utilizar otros recursos.",
  ],
  musical: [
    "Puedo cantar, tararear o silbar la música o canción que escuché alguna vez, reproduciéndola con fidelidad.",
    "Puedo componer melodías, aún sin saber sobre el lenguaje musical.",
    "Reproduzco o sigo distintos ritmos, golpeando algún elemento.",
    "Reconozco un tema musical cuando lo escucho.",
    "Con frecuencia hago la conexión entre alguna canción o melodía y algún evento de mi vida.",
    "Puedo cantar armoniosamente junto a otras personas.",
    "Aplico mentalmente sonidos o música a diversas situaciones o experiencias ya sea para conectar algo, disfrutar o poder recordar.",
    "Asocio la música con mis estados de ánimo.",
    "Sé tocar (o antes solía hacerlo) un instrumento musical.",
    "Me doy cuenta cuando un cantante o instrumentista está afinado o no.",
  ],
  cinestesicaCorporal: [
    "Tengo buen sentido del equilibrio y coordinación.",
    "Puedo manejar bien aparatos y vehículos.",
    "Tengo habilidad manual para desarmar y armar aparatos, máquinas u objetos.",
    "Soy hábil con las manos para realizar movimientos de precisión que requieran gran concentración.",
    "Soy efectivo/a en las actividades físicas y práctica de deportes o juegos de destreza.",
    "Aprendo rápido, sin mucha dificultad, a bailar una coreografía o baile nuevo.",
    "Suelo identificar y diferenciar objetos por el tacto (peso, temperatura, consistencia, etc.).",
    "Puedo orientarme en el espacio y con los objetos teniendo los ojos vendados o cerrados.",
    "Presto atención a mis sensaciones físicas para percibir e intuir situaciones y poder tomar decisiones.",
    "Expreso lo que siento con gestos y empleando mi cuerpo en general.",
  ],
  intrapersonal: [
    "Me gusta sentarme silenciosamente y reflexionar sobre mis sentimientos y pensamientos íntimos.",
    "Cuando me equivoco o hago algo mal busco aprender de eso.",
    "No me cuesta identificar mis estados de ánimo.",
    "Reflexiono acerca de cómo puedo mejorar mi forma de actuar o pensar.",
    "Reconozco mis fortalezas y mis debilidades.",
    "Tomo conciencia de las emociones que siento.",
    "Pido o acato sugerencias que sean para mejorar en algún aspecto personal.",
    "Acepto las frustraciones y busco cómo lograr lo que necesito por algún otro camino.",
    "Si estoy enojado/a o contento/a me doy cuenta en el momento del porqué es así.",
    "Distingo cuando puedo arreglarme solo y cuando necesito pedir ayuda.",
  ],
  interpersonal: [
    "Sé trabajar en compañía o equipo, cumpliendo mi rol.",
    "Soy capaz de convencer a otros para que sigan mis planes.",
    "Disfruto estar y comunicarme con gente que recién conozco en una fiesta o reunión.",
    "Puedo escuchar a los demás para entenderlos, aunque no esté de acuerdo con ellos.",
    "Solicito lo que necesito en forma directa y eficaz.",
    "Puedo negociar y llegar a acordar, aunque inicialmente haya muchas diferencias.",
    "Puedo captar lo que otros sienten y ayudarlos a sentirse mejor.",
    "Defiendo mis derechos o los ajenos, y me hago respetar en forma serena y firme.",
    "Me gusta reunir grupos de personas y ayudar a que se sientan a gusto.",
    "Puedo captar lo positivo y lo negativo de las personas, pero tiendo a resaltar lo positivo en vez de atacar o criticar.",
  ],
  naturalista: [
    "Reconozco e identifico una gran cantidad de plantas, diferenciándolas por sus características específicas.",
    "Encuentro relaciones entre el clima de un lugar, el tipo de ambiente o ecosistema.",
    "Soy sensible para captar las fuentes de contaminación ambiental en el lugar donde me encuentre.",
    "Reconozco y distingo los distintos elementos que componen un ecosistema y sus interacciones mutuas.",
    "Identifico con facilidad, ya sea por fotos o dibujos, las distintas especies de animales o plantas.",
    "Capto las características de animales o plantas que los adaptan a su medio y puedo relacionarlas con su entorno o forma de vida.",
    "Evalúo el impacto y las consecuencias ambientales de fuentes de contaminación.",
    "Capto las semejanzas y diferencias que hay entre distintos animales de una misma especie.",
    "Tengo facilidad para conocer y clasificar distintos tipos de animales, de plantas, de suelos o de rocas.",
    "En interacción directa con un ambiente natural, identifico las características que les son propias y lo distinguen de otro ecosistema.",
  ],
}

export type GardnerKey = keyof typeof gardnerQuestions

export const gardnerKeys: GardnerKey[] = [
  "logicoMatematica",
  "verbalLinguistica",
  "espacial",
  "musical",
  "cinestesicaCorporal",
  "intrapersonal",
  "interpersonal",
  "naturalista",
]

export const gardnerLabels: Record<GardnerKey, string> = {
  logicoMatematica:   "A. Lógico-Matemática",
  verbalLinguistica:  "B. Verbal-Lingüística",
  espacial:           "C. Espacial",
  musical:            "D. Musical",
  cinestesicaCorporal:"E. Cinestésica-Corporal",
  intrapersonal:      "F. Intrapersonal",
  interpersonal:      "G. Interpersonal",
  naturalista:        "H. Naturalista",
}

export const gardnerShortLabels: Record<GardnerKey, string> = {
  logicoMatematica:   "Lóg-Mat",
  verbalLinguistica:  "Verb-Ling",
  espacial:           "Espacial",
  musical:            "Musical",
  cinestesicaCorporal:"Cinestésica",
  intrapersonal:      "Intrap.",
  interpersonal:      "Interp.",
  naturalista:        "Naturalista",
}
