export const herrmannQuestions = {
  motivacion: [
    "Trabajar solo",
    "Expresar mis ideas",
    "Tener el control de la situación",
    "Provocar cambios",
    "Oír y hablar",
    "Crear o usar recursos visuales",
    "Prestarle atención a los detalles",
    "Aspectos técnicos",
    "Trabajar con personas",
    "Usar números, estadísticas",
    "Oportunidades para probar cosas nuevas",
    "Planificar",
    "Trabajar con comunicación",
    "Hacer que algo funcione",
    "Arriesgarse",
    "Analizar datos",
    "Lidiar con el futuro",
    "Producir y organizar",
    "Ser parte de un equipo",
    "Realizar las tareas siempre en el plazo previsto",
  ],
  aprendizaje: [
    "Evaluar y testar teorías",
    "Obtener y cuantificar hechos",
    "Oír y compartir ideas",
    "Usar mi imaginación",
    "Aplicar análisis y lógica",
    "Un ambiente bien informal",
    "Verificar mi comprensión",
    "Hacer experiencias prácticas",
    "Pensar sobre las ideas",
    "Confiar en las intuiciones",
    "Recibir informaciones paso a paso",
    "Tomar iniciativas",
    "Elaborar teorías",
    "Involucrarme emocionalmente",
    "Trabajar en grupo",
    "Orientaciones claras",
    "Descubrir cosas nuevas",
    "Criticar",
    "Visualizar rápidamente el cuadro general (el objetivo final)",
    "Adquirir habilidades por la práctica",
  ],
  aprendizajeModo: [
    "Materiales visuales",
    "Demostraciones",
    "Debates estructurados por el instructor",
    "Clases formales",
    "Experiencias",
    "Utilizando historias y música",
    "Ejercicios que usan la intuición",
    "Debate en grupo",
    "Ejercicios de análisis",
    "Actividades paso a paso con orden claro",
    "Analizando números, datos y hechos",
    "Ejemplos con metáforas",
    "Actividades paso a paso de refuerzo del contenido",
    "Lectura de libros-textos",
    "Discusiones de casos orientados hacia las personas",
    "Discusiones de casos orientados hacia los números y hechos",
    "Métodos tradicionales comprobados",
    "Agenda bien flexible",
    "Agenda estructurada con antecedencia",
    "Trabajos bien estructurados",
  ],
  tipoPregunta: ["¿Qué?", "¿Cómo?", "¿Por qué?", "¿Quién?"],
  meGusta: [
    "Descubrir",
    "Cuantificar",
    "Agrupar",
    "Organizar",
    "Conceptuar",
    "Analizar",
    "Sentir",
    "Practicar",
    "Teorizar",
    "Resumir",
    "Evaluar",
    "Reflexionar",
    "Procesar",
    "Ordenar",
    "Explorar",
    "Compartir",
  ],
  comprarCoche: [
    "Lo compra basado en la recomendación de amigos",
    "Se preocupa con el consumo de combustible",
    "Se preocupa con las formas, el color y la tecnología",
    "Verifica los equipos de seguridad y durabilidad",
    "Le da importancia a la 'sensación' de confort del vehículo",
    "Lo compara con otros vehículos",
    "Verifica el tamaño del baúl del coche",
    "Verifica si se encaja en su proyecto o sueño de vida",
    "Investiga y planea anticipadamente cómo va a utilizarlo",
    "Se preocupa con el costo y el valor de reventa",
    "Quiere 'amar' al coche",
    "Prefiere coches lanzados recientemente, novedades",
    "Se preocupa con los requisitos técnicos",
    "Verifica la facilidad de mantenimiento",
    "Le gusta probar un nuevo modelo o fabricante",
    "Se preocupa con la marca del fabricante",
    "Le da importancia a la opinión de las personas",
    "Quiere ver datos y estadísticas sobre el desempeño",
    "Se preocupa con la calidad de la atención de la concesionaria",
    "Analiza cómo el coche le será útil en el día a día",
  ],
  comprarCelular: [
    "Lo comprás porque es el que tienen todos tus amigos o el que te recomendaron",
    "Te encanta probar una marca o un sistema operativo que nunca usaste",
    "Querés que 'te enamore' apenas lo veas; que tenga toda la onda",
    "Sos de los que comparan mil modelos y miran reviews antes de decidir",
    "Te preocupa cuánto le dura la batería y que no te deje a gamba",
    "Para vos la marca es clave; dice mucho de quién sos",
    "Buscás el último modelo que salió, lo más nuevo de lo más nuevo",
    "Lo primero que mirás es cuánta memoria interna tiene para guardar todo",
    "Te importa muchísimo el diseño, los colores y que la cámara sea pro",
    "Te importa que a los demás les parezca un buen equipo cuando lo vean",
    "Te fijás en los detalles técnicos: procesador, memoria RAM y potencia",
    "Buscás que el celu encaje con tus proyectos (para crear contenido, trabajar o estudiar)",
    "Buscás que sea resistente (que si se te cae, no se haga mil pedazos)",
    "Querés ver los números reales: benchmarks, calidad de pantalla y velocidad",
    "Te fijás si es fácil de arreglar o si tiene buen servicio técnico",
    "Investigás semanas antes y planeás exactamente para qué lo vas a usar",
    "Le das importancia a que sea cómodo en la mano y se sienta bien al usarlo",
    "Te importa que la atención en el local sea buena y te asesoren bien",
    "Analizás qué tan útil te va a ser para lo que hacés todos los días (gaming, redes, etc.)",
    "Pensás en el precio y si después lo vas a poder vender a buen valor para cambiarlo",
  ],
  comportamiento: ["Me gusta Organizar", "Me gusta Compartir", "Me gusta Analizar", "Me gusta Descubrir"],
  estiloPalabras: [
    "Organizado",
    "Analítico",
    "Emocional",
    "Experimental",
    "Lógico",
    "Conceptual",
    "Perceptivo",
    "Secuencial",
    "Explorador",
    "Evaluador",
    "Activo",
    "Sentimental",
    "Preparado",
    "Cuantitativo",
    "Directo",
    "Teórico",
  ],
  desprecio: [
    "Maniático por los números",
    "De corazón blando",
    "Exigente, esforzado",
    "Que vive en la luna",
    "Tiene sed de poder",
    "Habla demasiado",
    "No decide solo",
    "No sabe concentrarse",
    "Frío, insensible",
    "Fácil de convencer",
    "Sin imaginación",
    "Loquito",
    "Calculista",
    "Ingenuo",
    "Intolerante",
    "Vago",
    "No se junta a los otros",
    "Ultrasensible",
    "Cuadrado",
    "Sin disciplina",
  ],
}
