export const mipsQuestions = [
  "Soy una persona tranquila y colaboradora.",
  "Siempre he hecho lo que he querido y he aceptado las consecuencias.",
  "Me gusta ser la persona que asume el control de las cosas.",
  "Tengo una manera habitual de hacer las cosas, con lo que evito equivocarme.",
  "Respondo mensajes o comunicaciones el mismo día que los recibo.",
  "A veces me las arreglo para arruinar las cosas buenas que me pasan.",
  "Ya no encuentro tantas cosas nuevas que me gustan como antes",
  "Preferiría ser un seguidor más que un líder.",
  "Me esfuerzo por llegar a ser popular.",
  "Siempre he tenido talento para tener éxito en lo que hago.",
  "Con frecuencia me doy cuenta de que he sido tratado injustamente.",
  "Me siento incómodo cuando me tratan bien.",
  "Con frecuencia me siento tenso en situaciones sociales.",
  "Creo que la policía / patovica / preceptores abusan del poder que tiene.",
  "Algunas veces he tenido que ser bastante brusco con la gente.",
  "Los niños deben obedecer siempre las indicaciones de sus mayores.",
  "A menudo me molestan la forma en que se hacen las cosas.",
  "A menudo espero que me pase lo peor.",
  "No me importaría tener pocos amigos.",
  "Soy tímido e inhibido en situaciones sociales.",
  "Aunque esté en desacuerdo, por lo general dejo que la gente haga lo que quiera.",
  "Es imposible pretender que las personas digan siempre la verdad.",
  "Puedo hacer comentarios desagradables si considero que las personas se los merecen.",
  "Me gusta cumplir con lo establecido y hacer lo que se espera de mí.",
  "Muy poco de lo que hago es valorado por los demás.",
  "Casi todo lo que intento hacer me resulta fácil.",
  "Últimamente me he convertido en una persona más encerrada en mí misma.",
  "Tiendo a hacer un drama de las cosas que me pasan.",
  "Siempre trato de hacer lo que es correcto.",
  "Dependo poco de la amistad de los demás.",
  "Cuando hay un límite claro (horario, cantidad, consigna), trato de no pasarme",
  "Los castigos nunca me han impedido hacer lo que he querido.",
  "Me gusta organizar todas las cosas hasta en sus mínimos detalles.",
  "A menudo los demás logran irritarme.",
  "Jamás he desobedecido las indicaciones de mis padres.",
  "Siempre logro conseguir lo que quiero aunque tenga que presionar a los demás.",
  "Nada es más importante que proteger la reputación personal.",
  "Los demás tienen mejores oportunidades que yo.",
  "Ya no expreso lo que realmente siento.",
  "Es imposible que lo que tengo que decir interese a los demás.",
  "Me esfuerzo por conocer gente interesante y tener aventuras.",
  "Me tomo con poca seriedad muchas de las responsabilidades que tengo.",
  "Soy una persona dura, nada sentimental.",
  "Pocas cosas en la vida pueden conmoverme.",
  "Me pone muy nervioso el tener que conocer y conversar con gente nueva.",
  "Soy una persona colaboradora que cede ante los demás.",
  "Actúo en función del momento, dependiendo de las circunstancias.",
  "Primero planifico y luego sigo activamente el plan trazado.",
  "A menudo me he sentido inquieto con ganas de irme a cualquier parte.",
  "Lo mejor es controlar nuestras emociones.",
  "Desearía que la gente no me culpara a mí cuando algo sale mal.",
  "Probablemente soy mi peor enemigo.",
  "Tengo muy pocos lazos afectivos fuertes con otras personas.",
  "Me siento intranquilo con personas que no conozco muy bien.",
  "Es correcto tratar de burlar la ley sin dejar de cumplirla.",
  "Hago mucho por los demás, pero ellos hacen poco por mí.",
  "Siempre he creído que los demás no tienen buena opinión de mí.",
  "Tengo mucha confianza en mí mismo.",
  "Sistemáticamente ordeno mis papeles y materiales de trabajo.",
  "Mi experiencia me ha enseñado que las cosas buenas duran poco.",
  "Algunos dicen que me gusta hacerme la víctima.",
  "Me siento mejor cuando estoy solo.",
  "Me pongo más tenso que los demás frente a situaciones nuevas.",
  "Siempre trato de evitar las discusiones, por más que esté convencido de tener razón.",
  "Busco situaciones novedosas y excitantes para mí.",
  "Hubo épocas en que mis padres tuvieron problemas por mi comportamiento.",
  "Siempre termino mi trabajo antes de descansar.",
  "Otros consiguen cosas que yo no logro.",
  "A veces siento que merezco ser infeliz.",
  "Espero que las cosas sigan su curso antes de decidir qué hacer.",
  "Procuro ocuparme más de los demás que de mí mismo.",
  "A menudo creo que mi vida va de mal en peor.",
  "El solo hecho de estar con otras personas me hace sentir inspirado.",
  "Suelo respetar las reglas, incluso cuando nadie está controlando",
  "Uso mi cabeza y no mi corazón para tomar decisiones.",
  "Generalmente suelo guiarme de mis intuiciones más que por la información que tengo sobre algo.",
  "Jamás envidio los éxitos de los demás.",
  "En el colegio me gustaban más los cursos prácticos que los teóricos.",
  "Planifico las cosas con anticipación y actúo enérgicamente para que mis planes se cumplan.",
  "Mi corazón controla mi cerebro.",
  "Siempre puedo ver el lado positivo de la vida.",
  "A menudo espero que alguien solucione mis problemas.",
  "Hago lo que quiero, sin pensar cómo va a afectar a los otros.",
  "Reacciono con rapidez ante cualquier situación que pueda llegar a ser un problema para mí.",
  "Sólo me siento una buena persona cuando ayudo a los demás.",
  "Si algo sale mal, aunque no sea importante, se me arruina todo el día.",
  "Disfruto más de mis fantasías que de la realidad cotidiana.",
  "Me siento satisfecho dejando que las cosas ocurran.",
  "Trato de ser más lógico que emocional.",
  "Prefiero las cosas que se pueden ver y tocar antes que las que sólo se imaginan.",
  "Me resulta difícil conversar con alguien que acabo de conocer.",
  "Ser afectuoso es más importante que ser frío y calculador.",
  "Las predicciones sobre el futuro son más interesantes para mí que los hechos del pasado.",
  "Me resulta fácil disfrutar de las cosas.",
  "Me siento incapaz de influir en el mundo que me rodea.",
  "Vivo según mis propias necesidades y no basado en las de los demás.",
  "Nunca espero que las cosas pasen, hago que sucedan como yo quiero.",
  "Evito contestar bruscamente cuando estoy molesto.",
  "La necesidad de ayudar a otros guía mi vida.",
  "A menudo me siento muy tenso, a la espera de que algo salga mal.",
  "Nunca intenté copiar en un examen.",
  "Siempre soy frío y objetivo en el trato con los demás.",
  "Prefiero aprender a manejar un aparato antes que especular sobre por qué funciona de ese modo.",
  "Soy una persona difícil de conocer bien.",
  "Paso mucho tiempo pensando en los misterios de la vida.",
  "Es fácil para mí controlar mis estados de ánimo.",
  "Soy algo pasivo y lento en temas relacionados con la organización de mi vida.",
  "Hago lo que quiero sin importarme el complacer a otros.",
  "Jamás haría algo malo, por más fuerte que sea la tentación de hacerlo.",
  "Mis amigos y mis familiares recurren a mí en primer lugar para encontrar afecto y apoyo.",
  "Aunque todo esté bien, generalmente pienso que va a pasar lo peor.",
  "Planifico y organizo con cuidado mi trabajo antes de empezar a hacerlo.",
  "Soy impersonal y objetivo al tratar de resolver un problema.",
  "Soy una persona realista a la que no le gustan las especulaciones.",
  "Algunos de mis mejores amigos desconocen lo que realmente siento.",
  "La gente piensa que soy una persona más racional que afectiva.",
  "Mi sentido de la realidad es mejor que mi imaginación.",
  "Primero me preocupo por mí y después de los demás.",
  "Dedico mucho esfuerzo para que las cosas me salgan bien.",
  "Siempre mantengo la compostura, sin importar lo que esté pasando.",
  "Demuestro mucho afecto hacia mis amigos.",
  "Muy pocas cosas me han salido bien.",
  "Me gusta conocer gente nueva y saber cosas sobre sus vidas.",
  "Puedo ignorar aspectos emocionales y afectivos en mi trabajo.",
  "Prefiero ocuparme de realidades y no de posibilidades.",
  "Necesito mucho tiempo para poder estar a solas con mis pensamientos.",
  "Los sentimientos son más importantes que la lógica de la mente.",
  "Me gustan más los soñadores que los realistas.",
  "Soy más capaz que los demás de reírme de los problemas.",
  "Es poco lo que puedo hacer, así que prefiero esperar a ver qué pasa.",
  "Nunca me pongo a discutir, aunque esté muy enojado.",
  "Expreso lo que pienso de manera franca y abierta.",
  "Me preocupo por el trabajo que hay que realizar y no por lo que siente la gente que participa en su realización.",
  "Para mí lo ideal sería trabajar con ideas creativas.",
  "Soy el tipo de persona que no se toma la vida muy en serio, prefiero ser más espectador que actor.",
  "Me desagrada que voy a depender de alguien en mi trabajo.",
  "Trato de asegurar que las cosas salgan como yo quiero.",
  "Disfruto más de las realidades concretas que de las fantasías.",
  "Muchas cosas sin importancia me ponen de mal humor.",
  "Aprendo mejor observando y hablando con la gente.",
  "No me satisface dejar que las cosas sucedan y simplemente contemplarlas.",
  "No me atrae conocer gente nueva.",
  "Pocas veces sé cómo mantener una conversación.",
  "Siempre tengo en cuenta los sentimientos de las personas.",
  "Confío más en mis intuiciones que en mis observaciones.",
  "Trato de no actuar hasta saber qué van a hacer los demás.",
  "Me gusta tomar mis propias decisiones, evitando los consejos de los otros.",
  "Muchas veces me siento muy mal sin saber por qué.",
  "Me gusta ser popular y participar en muchas actividades sociales.",
  "Raramente cuento a otro lo que pienso.",
  "Me entusiasman casi todas las actividades que realizo.",
  "Para mí es una práctica constante depender de mí mismo y no de otros.",
  "La mayor parte del tiempo la dedico a organizar lo que tengo que hacer.",
  "No hay nada mejor que el afecto que se siente estando con mi familia",
  "Algunas veces estoy tenso o deprimido sin saber por qué.",
  "Disfruto conversando sobre temas o sucesos místicos.",
  "Decido cuáles son las cosas prioritarias y luego actúo firmemente para poder lograrlas.",
  "No dudo en orientar a las personas hacia lo que yo creo que es mejor para ellas.",
  "Me siento orgulloso de ser eficiente y organizado.",
  "Realmente me desagradan las personas que se convierten en líderes sin razones que lo justifiquen.",
  "Soy ambicioso en mis metas.",
  "Sé cómo agradar a la gente.",
  "La gente puede confiar en que voy a hacer bien mi trabajo.",
  "Los demás me consideran una persona más afectiva que racional.",
  "Estaría dispuesto a trabajar mucho tiempo para poder llegar a ser alguien importante.",
  "Me gustaría mucho poder vender nuevas ideas o productos a la gente.",
  "Generalmente logro convencer a los demás para que hagan exactamente lo que yo quiero.",
  "Me gustan los trabajos en los que hay que prestar mucha atención en los detalles.",
  "Soy muy introspectivo, siempre trato de entender mis pensamientos y emociones.",
  "Confío mucho en mis habilidades sociales.",
  "Evalúo las situaciones rápidamente y luego actúo para que las cosas salgan como yo quiero.",
  "En una discusión soy capaz de convencer a casi todos para que apoyen mi posición.",
  "Soy capaz de llevar a cabo cualquier trabajo, pese a los obstáculos que puedan presentarse.",
  "Como si fuera un buen vendedor, puedo influir con éxito sobre los demás, con modales agradables.",
  "Conocer gente nueva es un objetivo importante para mí.",
  "Al tomar decisiones creo que lo más importante es pensar en el bienestar de la gente involucrada.",
  "Tengo paciencia para realizar trabajos que requieren mucha precisión.",
  "Mi imaginación es superior a mi sentido de la realidad.",
  "Estoy motivado para llegar a ser uno de los mejores en mi campo de trabajo.",
  "Tengo un comportamiento que logra ganarme la aprobación de la gente.",
]
