export const proyectivasQuestions = [
  "Siempre me gustó...",
  "Acceder a la universidad hoy...",
  "En mi casa...",
  "Para trabajar es importante...",
  "El año que viene...",
  "Mis profesores piensan que yo...",
  "Las chicas/os que estudian...",
  "Conseguir trabajo hoy...",
  "Sin un título...",
  "Si se me presenta una dificultad...",
  "Las carreras largas...",
  "Si tengo que mantener una familia...",
  "Una persona adulta...",
  "Sin un trabajo...",
  "Elegir...",
  "A veces me da miedo...",
  "Si quiero tener una buena posición económica...",
  "Estudiar en grupo...",
  "Si yo pudiera...",
  "Hacer cursos fuera de la universidad...",
  "Cuando tenga hijos...",
  "Terminar una carrera...",
  "Para organizar mejor mi tiempo...",
  "Las mujeres que trabajan...",
  "Hacerse de amigos en la universidad...",
  "Mis padres quisieran que yo...",
  "Hacer una carrera corta...",
  "No tener hijos...",
  "Presentarme a un examen...",
  "Dentro de diez años...",
  "Para elegir hago ta-te-ti...",
  "Si yo fuera rica/o podría...",
  "Rara vez tomo una decisión importante sin consultar con alguien...",
  "Lo que más me atrae de un trabajo es...",
  "Me resulta difícil...",
  "En esta sociedad, más vale la pena ganar plata que...",
  "Me da miedo equivocarme...",
  "Cuando dudo entre dos cosas...",
  "En la vida, lo más importante es...",
  "Antes de hacer algo importante pienso...",
  "Pensar en el futuro me asusta muchísimo...",
  "Lo que más me pone nerviosa/o es...",
  "La mayor satisfacción en un trabajo es...",
  "La sociedad espera que una/o sea una persona...",
  "Es difícil elegir una profesión cuando...",
  "En la vida quiero llegar a ser...",
  "El problema con la mayor parte de los trabajos es...",
  "Cuando tengo que tomar una decisión me resulta tan difícil que...",
  "Si no estudiara sería...",
  "Siempre quise viajar por...",
  "Lo que más me preocupa es...",
  "El deseo más grande de un profesional es...",
  "Cuando sea mayor podré...",
  "Necesito que me entiendan...",
  "Una profesión brinda la oportunidad para...",
  "Lo que más quiero de un trabajo es...",
  "Lo difícil de tomar una decisión es...",
  "Lo que más me disgusta de un trabajo es...",
  "Puedo intentar un cambio pero...",
  "Yo soy...",
  "Los demás...",
  "Siento que los adultos que tienen autoridad sobre mí (profes, directivos) a veces son...",
  "Cuando se me acerca un profe o alguien que manda, yo..",
  "Las personas con autoridad me inspiran...",
]
