export const riasecSections = {
  personality: {
    R: [
      "Dinámico",
      "Concreto",
      "Conservador",
      "Franco",
      "Independiente",
      "Persistente",
      "Práctico",
      "Bien coordinado",
      "Rígido",
      "Fuerte",
      "Ahorrador",
      "Tradicional",
      "Individualista",
    ],
    I: [
      "Original",
      "Metódico",
      "Explorador",
      "Independiente",
      "Investigador",
      "Intelectual",
      "Lógico",
      "Observador",
      "Racional",
      "Curioso",
      "Reservado",
      "Preciso",
      "Investigativo",
    ],
    A: [
      "Soñador",
      "Informal",
      "Emocional",
      "Impulsivo",
      "Imaginativo",
      "Original",
      "Espontáneo",
      "No conformista",
      "Expresivo",
      "Independiente",
      "Práctico",
      "Sensible",
      "Creativo",
    ],
    S: [
      "Cálido",
      "Sensible",
      "Cooperativo",
      "Honesto",
      "Amigable",
      "Generoso",
      "Responsable",
      "Genuino",
      "Perceptivo",
      "Sociable",
      "Comprensivo",
      "Soñador",
      "Prudente",
    ],
    E: [
      "Aventurero",
      "Dinámico",
      "Dominante",
      "Popular",
      "Seguro de sí",
      "Sociable",
      "Curioso",
      "Extrovertido",
      "Optimista",
      "Colaborador",
      "Persuasivo",
      "Decidido",
      "Competitivo",
    ],
    C: [
      "Preciso",
      "Ordenado",
      "Cuidadoso",
      "Organizado",
      "Conformista",
      "Conservador",
      "Eficiente",
      "Prudente",
      "Detallista",
      "Responsable",
      "Práctico",
      "Predecible",
      "Callado",
    ],
  },
  habilidades: {
    R: [
      "Mecánica",
      "Atlética",
      "Manual",
      "Precisión",
      "Practicidad",
      "Estabilidad",
      "Analítica",
      "Crítica",
      "Uso del cuerpo",
      "Espacial",
    ],
    I: [
      "Analítica",
      "Abstracta",
      "Matemática",
      "Científica",
      "Verbal",
      "Resolutiva",
      "Metódica",
      "Observación",
      "Paciencia",
      "Investigación",
    ],
    A: [
      "Creativa",
      "Expresiva",
      "Intuitiva",
      "Introspectiva",
      "Musical",
      "Diseño",
      "Espacial",
      "Imaginación",
      "Detalle",
      "Innovación",
    ],
    S: [
      "Enseñanza",
      "Comprensión",
      "Escucha",
      "Ayuda al otro",
      "Comunicación",
      "Imaginación",
      "Responsabilidad",
      "Mediador",
      "Persuasión",
      "Astucia / viveza",
    ],
    E: [
      "Persuasión",
      "Responsabilidad",
      "Liderazgo",
      "Comunicación",
      "Expresión oral",
      "Organización",
      "Objetividad",
      "Practicidad",
      "Tolerancia",
      "Ambición",
    ],
    C: [
      "Cálculo",
      "Finanzas",
      "Prolijidad",
      "Planificación",
      "Método",
      "Orden",
      "Responsabilidad",
      "Practicidad",
      "Detalle",
      "Exactitud",
    ],
  },
  intereses: {
    R: ["Cálculo", "Científico", "Manual", "Ser preciso", "Planificación"],
    I: ["Ordenar", "Numérico", "Análisis/síntesis", "Orden/precisión", "Investigación"],
    A: ["Estético", "Equilibrado", "Manual", "Visual", "Auditivo"],
    S: ["Precisión verbal", "Organización", "Comunicación", "Ayuda", "Justicia"],
    E: ["Organización", "Supervisión", "Colaboración", "Análisis/síntesis", "Estrategias"],
    C: ["Orden", "Supervisión", "Computación", "Detalle", "Cálculo"],
  },
  motivaciones: {
    R: ["Lo tradicional", "Vida al aire libre", "Trabajo manual", "Sentido común", "Naturaleza", "Deportes"],
    I: ["Conocimiento", "Resolución de problemas", "Independencia", "Teorías", "Ciencia", "Curiosidad"],
    A: ["Ayuda", "Arte", "Lograr armonía", "Observación", "Expresión", "La belleza"],
    S: ["Cooperación", "Trabajo en equipo", "Comunicación", "Protección", "Curar", "El desarrollo personal"],
    E: ["Desafíos", "Competencia", "Organización", "Poder/servicio", "El estatus", "Emprender"],
    C: ["Seguridad", "Precisión", "Eficiencia", "Estadísticas", "Métodos", "Pertenencia"],
  },
}

export const riasecLabels = {
  R: "Realista",
  I: "Investigador",
  A: "Artístico",
  S: "Social",
  E: "Emprendedor",
  C: "Convencional",
}
